; Auto-generated. Do not edit!


(cl:in-package py_trees_msgs-msg)


;//! \htmlinclude RotateFeedback.msg.html

(cl:defclass <RotateFeedback> (roslisp-msg-protocol:ros-message)
  ((percentage_completed
    :reader percentage_completed
    :initarg :percentage_completed
    :type cl:float
    :initform 0.0)
   (angle_rotated
    :reader angle_rotated
    :initarg :angle_rotated
    :type cl:float
    :initform 0.0))
)

(cl:defclass RotateFeedback (<RotateFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RotateFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RotateFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name py_trees_msgs-msg:<RotateFeedback> is deprecated: use py_trees_msgs-msg:RotateFeedback instead.")))

(cl:ensure-generic-function 'percentage_completed-val :lambda-list '(m))
(cl:defmethod percentage_completed-val ((m <RotateFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader py_trees_msgs-msg:percentage_completed-val is deprecated.  Use py_trees_msgs-msg:percentage_completed instead.")
  (percentage_completed m))

(cl:ensure-generic-function 'angle_rotated-val :lambda-list '(m))
(cl:defmethod angle_rotated-val ((m <RotateFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader py_trees_msgs-msg:angle_rotated-val is deprecated.  Use py_trees_msgs-msg:angle_rotated instead.")
  (angle_rotated m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RotateFeedback>) ostream)
  "Serializes a message object of type '<RotateFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percentage_completed))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'angle_rotated))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RotateFeedback>) istream)
  "Deserializes a message object of type '<RotateFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percentage_completed) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'angle_rotated) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RotateFeedback>)))
  "Returns string type for a message object of type '<RotateFeedback>"
  "py_trees_msgs/RotateFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RotateFeedback)))
  "Returns string type for a message object of type 'RotateFeedback"
  "py_trees_msgs/RotateFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RotateFeedback>)))
  "Returns md5sum for a message object of type '<RotateFeedback>"
  "f1088922e17b4a9f4319356ac8d99645")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RotateFeedback)))
  "Returns md5sum for a message object of type 'RotateFeedback"
  "f1088922e17b4a9f4319356ac8d99645")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RotateFeedback>)))
  "Returns full string definition for message of type '<RotateFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%####################~%# Feedback~%####################~%~%float32 percentage_completed~%float32 angle_rotated          # in radians~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RotateFeedback)))
  "Returns full string definition for message of type 'RotateFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%####################~%# Feedback~%####################~%~%float32 percentage_completed~%float32 angle_rotated          # in radians~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RotateFeedback>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RotateFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RotateFeedback
    (cl:cons ':percentage_completed (percentage_completed msg))
    (cl:cons ':angle_rotated (angle_rotated msg))
))
