; Auto-generated. Do not edit!


(cl:in-package py_trees_msgs-msg)


;//! \htmlinclude RotateGoal.msg.html

(cl:defclass <RotateGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass RotateGoal (<RotateGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RotateGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RotateGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name py_trees_msgs-msg:<RotateGoal> is deprecated: use py_trees_msgs-msg:RotateGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RotateGoal>) ostream)
  "Serializes a message object of type '<RotateGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RotateGoal>) istream)
  "Deserializes a message object of type '<RotateGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RotateGoal>)))
  "Returns string type for a message object of type '<RotateGoal>"
  "py_trees_msgs/RotateGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RotateGoal)))
  "Returns string type for a message object of type 'RotateGoal"
  "py_trees_msgs/RotateGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RotateGoal>)))
  "Returns md5sum for a message object of type '<RotateGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RotateGoal)))
  "Returns md5sum for a message object of type 'RotateGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RotateGoal>)))
  "Returns full string definition for message of type '<RotateGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%###############################################################################~%# Rotate~%###############################################################################~%#~%# Rotates the robot a full 2pi radians.~%# Used for the py_trees_ros mocking demos/tests!~%#~%###############################################################################~%~%####################~%# Goal~%####################~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RotateGoal)))
  "Returns full string definition for message of type 'RotateGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%###############################################################################~%# Rotate~%###############################################################################~%#~%# Rotates the robot a full 2pi radians.~%# Used for the py_trees_ros mocking demos/tests!~%#~%###############################################################################~%~%####################~%# Goal~%####################~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RotateGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RotateGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'RotateGoal
))
