; Auto-generated. Do not edit!


(cl:in-package hri_msgs-msg)


;//! \htmlinclude FacialLandmarks.msg.html

(cl:defclass <FacialLandmarks> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (landmarks
    :reader landmarks
    :initarg :landmarks
    :type (cl:vector hri_msgs-msg:NormalizedPointOfInterest2D)
   :initform (cl:make-array 0 :element-type 'hri_msgs-msg:NormalizedPointOfInterest2D :initial-element (cl:make-instance 'hri_msgs-msg:NormalizedPointOfInterest2D)))
   (height
    :reader height
    :initarg :height
    :type cl:integer
    :initform 0)
   (width
    :reader width
    :initarg :width
    :type cl:integer
    :initform 0))
)

(cl:defclass FacialLandmarks (<FacialLandmarks>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FacialLandmarks>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FacialLandmarks)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hri_msgs-msg:<FacialLandmarks> is deprecated: use hri_msgs-msg:FacialLandmarks instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <FacialLandmarks>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hri_msgs-msg:header-val is deprecated.  Use hri_msgs-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'landmarks-val :lambda-list '(m))
(cl:defmethod landmarks-val ((m <FacialLandmarks>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hri_msgs-msg:landmarks-val is deprecated.  Use hri_msgs-msg:landmarks instead.")
  (landmarks m))

(cl:ensure-generic-function 'height-val :lambda-list '(m))
(cl:defmethod height-val ((m <FacialLandmarks>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hri_msgs-msg:height-val is deprecated.  Use hri_msgs-msg:height instead.")
  (height m))

(cl:ensure-generic-function 'width-val :lambda-list '(m))
(cl:defmethod width-val ((m <FacialLandmarks>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hri_msgs-msg:width-val is deprecated.  Use hri_msgs-msg:width instead.")
  (width m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<FacialLandmarks>)))
    "Constants for message type '<FacialLandmarks>"
  '((:RIGHT_EAR . 0)
    (:RIGHT_PROFILE_1 . 1)
    (:RIGHT_PROFILE_2 . 2)
    (:RIGHT_PROFILE_3 . 3)
    (:RIGHT_PROFILE_4 . 4)
    (:RIGHT_PROFILE_5 . 5)
    (:RIGHT_PROFILE_6 . 6)
    (:RIGHT_PROFILE_7 . 7)
    (:MENTON . 8)
    (:LEFT_EAR . 16)
    (:LEFT_PROFILE_1 . 15)
    (:LEFT_PROFILE_2 . 14)
    (:LEFT_PROFILE_3 . 13)
    (:LEFT_PROFILE_4 . 12)
    (:LEFT_PROFILE_5 . 11)
    (:LEFT_PROFILE_6 . 10)
    (:LEFT_PROFILE_7 . 9)
    (:RIGHT_EYEBROW_OUTSIDE . 17)
    (:RIGHT_EYEBROW_1 . 18)
    (:RIGHT_EYEBROW_2 . 19)
    (:RIGHT_EYEBROW_3 . 20)
    (:RIGHT_EYEBROW_INSIDE . 21)
    (:RIGHT_EYE_OUTSIDE . 36)
    (:RIGHT_EYE_TOP_1 . 37)
    (:RIGHT_EYE_TOP_2 . 38)
    (:RIGHT_EYE_INSIDE . 39)
    (:RIGHT_EYE_BOTTOM_1 . 41)
    (:RIGHT_EYE_BOTTOM_2 . 40)
    (:RIGHT_PUPIL . 68)
    (:LEFT_EYEBROW_OUTSIDE . 26)
    (:LEFT_EYEBROW_1 . 25)
    (:LEFT_EYEBROW_2 . 24)
    (:LEFT_EYEBROW_3 . 23)
    (:LEFT_EYEBROW_INSIDE . 22)
    (:LEFT_EYE_OUTSIDE . 45)
    (:LEFT_EYE_TOP_1 . 44)
    (:LEFT_EYE_TOP_2 . 43)
    (:LEFT_EYE_INSIDE . 42)
    (:LEFT_EYE_BOTTOM_1 . 46)
    (:LEFT_EYE_BOTTOM_2 . 47)
    (:LEFT_PUPIL . 69)
    (:SELLION . 27)
    (:NOSE_1 . 28)
    (:NOSE_2 . 29)
    (:NOSE . 30)
    (:NOSTRIL_1 . 31)
    (:NOSTRIL_2 . 32)
    (:NOSTRIL_3 . 33)
    (:NOSTRIL_4 . 34)
    (:NOSTRIL_5 . 35)
    (:MOUTH_OUTER_RIGHT . 48)
    (:MOUTH_OUTER_TOP_1 . 49)
    (:MOUTH_OUTER_TOP_2 . 50)
    (:MOUTH_OUTER_TOP_3 . 51)
    (:MOUTH_OUTER_TOP_4 . 52)
    (:MOUTH_OUTER_TOP_5 . 53)
    (:MOUTH_OUTER_LEFT . 54)
    (:MOUTH_OUTER_BOTTOM_1 . 59)
    (:MOUTH_OUTER_BOTTOM_2 . 58)
    (:MOUTH_OUTER_BOTTOM_3 . 57)
    (:MOUTH_OUTER_BOTTOM_4 . 56)
    (:MOUTH_OUTER_BOTTOM_5 . 55)
    (:MOUTH_INNER_RIGHT . 60)
    (:MOUTH_INNER_TOP_1 . 61)
    (:MOUTH_INNER_TOP_2 . 62)
    (:MOUTH_INNER_TOP_3 . 63)
    (:MOUTH_INNER_LEFT . 64)
    (:MOUTH_INNER_BOTTOM_1 . 67)
    (:MOUTH_INNER_BOTTOM_2 . 66)
    (:MOUTH_INNER_BOTTOM_3 . 65))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'FacialLandmarks)))
    "Constants for message type 'FacialLandmarks"
  '((:RIGHT_EAR . 0)
    (:RIGHT_PROFILE_1 . 1)
    (:RIGHT_PROFILE_2 . 2)
    (:RIGHT_PROFILE_3 . 3)
    (:RIGHT_PROFILE_4 . 4)
    (:RIGHT_PROFILE_5 . 5)
    (:RIGHT_PROFILE_6 . 6)
    (:RIGHT_PROFILE_7 . 7)
    (:MENTON . 8)
    (:LEFT_EAR . 16)
    (:LEFT_PROFILE_1 . 15)
    (:LEFT_PROFILE_2 . 14)
    (:LEFT_PROFILE_3 . 13)
    (:LEFT_PROFILE_4 . 12)
    (:LEFT_PROFILE_5 . 11)
    (:LEFT_PROFILE_6 . 10)
    (:LEFT_PROFILE_7 . 9)
    (:RIGHT_EYEBROW_OUTSIDE . 17)
    (:RIGHT_EYEBROW_1 . 18)
    (:RIGHT_EYEBROW_2 . 19)
    (:RIGHT_EYEBROW_3 . 20)
    (:RIGHT_EYEBROW_INSIDE . 21)
    (:RIGHT_EYE_OUTSIDE . 36)
    (:RIGHT_EYE_TOP_1 . 37)
    (:RIGHT_EYE_TOP_2 . 38)
    (:RIGHT_EYE_INSIDE . 39)
    (:RIGHT_EYE_BOTTOM_1 . 41)
    (:RIGHT_EYE_BOTTOM_2 . 40)
    (:RIGHT_PUPIL . 68)
    (:LEFT_EYEBROW_OUTSIDE . 26)
    (:LEFT_EYEBROW_1 . 25)
    (:LEFT_EYEBROW_2 . 24)
    (:LEFT_EYEBROW_3 . 23)
    (:LEFT_EYEBROW_INSIDE . 22)
    (:LEFT_EYE_OUTSIDE . 45)
    (:LEFT_EYE_TOP_1 . 44)
    (:LEFT_EYE_TOP_2 . 43)
    (:LEFT_EYE_INSIDE . 42)
    (:LEFT_EYE_BOTTOM_1 . 46)
    (:LEFT_EYE_BOTTOM_2 . 47)
    (:LEFT_PUPIL . 69)
    (:SELLION . 27)
    (:NOSE_1 . 28)
    (:NOSE_2 . 29)
    (:NOSE . 30)
    (:NOSTRIL_1 . 31)
    (:NOSTRIL_2 . 32)
    (:NOSTRIL_3 . 33)
    (:NOSTRIL_4 . 34)
    (:NOSTRIL_5 . 35)
    (:MOUTH_OUTER_RIGHT . 48)
    (:MOUTH_OUTER_TOP_1 . 49)
    (:MOUTH_OUTER_TOP_2 . 50)
    (:MOUTH_OUTER_TOP_3 . 51)
    (:MOUTH_OUTER_TOP_4 . 52)
    (:MOUTH_OUTER_TOP_5 . 53)
    (:MOUTH_OUTER_LEFT . 54)
    (:MOUTH_OUTER_BOTTOM_1 . 59)
    (:MOUTH_OUTER_BOTTOM_2 . 58)
    (:MOUTH_OUTER_BOTTOM_3 . 57)
    (:MOUTH_OUTER_BOTTOM_4 . 56)
    (:MOUTH_OUTER_BOTTOM_5 . 55)
    (:MOUTH_INNER_RIGHT . 60)
    (:MOUTH_INNER_TOP_1 . 61)
    (:MOUTH_INNER_TOP_2 . 62)
    (:MOUTH_INNER_TOP_3 . 63)
    (:MOUTH_INNER_LEFT . 64)
    (:MOUTH_INNER_BOTTOM_1 . 67)
    (:MOUTH_INNER_BOTTOM_2 . 66)
    (:MOUTH_INNER_BOTTOM_3 . 65))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FacialLandmarks>) ostream)
  "Serializes a message object of type '<FacialLandmarks>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'landmarks))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'landmarks))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'height)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'height)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'height)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'height)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'width)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'width)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'width)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'width)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FacialLandmarks>) istream)
  "Deserializes a message object of type '<FacialLandmarks>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'landmarks) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'landmarks)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'hri_msgs-msg:NormalizedPointOfInterest2D))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'height)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'height)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'height)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'height)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'width)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'width)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'width)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'width)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FacialLandmarks>)))
  "Returns string type for a message object of type '<FacialLandmarks>"
  "hri_msgs/FacialLandmarks")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FacialLandmarks)))
  "Returns string type for a message object of type 'FacialLandmarks"
  "hri_msgs/FacialLandmarks")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FacialLandmarks>)))
  "Returns md5sum for a message object of type '<FacialLandmarks>"
  "c779d9fd02c1af8ab6a1712921ab9da5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FacialLandmarks)))
  "Returns md5sum for a message object of type 'FacialLandmarks"
  "c779d9fd02c1af8ab6a1712921ab9da5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FacialLandmarks>)))
  "Returns full string definition for message of type '<FacialLandmarks>"
  (cl:format cl:nil "# This message contains a list of facial features detected on a face~%# (0, 0) is at top-left corner of image~%# Features' coordinates are expressed in normalised pixel coordinates ~%# (in the range [0., 1.]), from the top-left corner.~%Header header~%~%# Facial landmarks codes~%# Follows dlib and OpenPose convention~%# https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/02_output.md#face-output-format~%uint8 RIGHT_EAR=0~%uint8 RIGHT_PROFILE_1=1~%uint8 RIGHT_PROFILE_2=2~%uint8 RIGHT_PROFILE_3=3~%uint8 RIGHT_PROFILE_4=4~%uint8 RIGHT_PROFILE_5=5~%uint8 RIGHT_PROFILE_6=6~%uint8 RIGHT_PROFILE_7=7~%~%uint8 MENTON=8~%~%uint8 LEFT_EAR=16~%uint8 LEFT_PROFILE_1=15~%uint8 LEFT_PROFILE_2=14~%uint8 LEFT_PROFILE_3=13~%uint8 LEFT_PROFILE_4=12~%uint8 LEFT_PROFILE_5=11~%uint8 LEFT_PROFILE_6=10~%uint8 LEFT_PROFILE_7=9~%~%uint8 RIGHT_EYEBROW_OUTSIDE=17~%uint8 RIGHT_EYEBROW_1=18~%uint8 RIGHT_EYEBROW_2=19~%uint8 RIGHT_EYEBROW_3=20~%uint8 RIGHT_EYEBROW_INSIDE=21~%~%uint8 RIGHT_EYE_OUTSIDE=36~%uint8 RIGHT_EYE_TOP_1=37~%uint8 RIGHT_EYE_TOP_2=38~%uint8 RIGHT_EYE_INSIDE=39~%uint8 RIGHT_EYE_BOTTOM_1=41~%uint8 RIGHT_EYE_BOTTOM_2=40~%~%uint8 RIGHT_PUPIL=68~%~%uint8 LEFT_EYEBROW_OUTSIDE=26~%uint8 LEFT_EYEBROW_1=25~%uint8 LEFT_EYEBROW_2=24~%uint8 LEFT_EYEBROW_3=23~%uint8 LEFT_EYEBROW_INSIDE=22~%~%uint8 LEFT_EYE_OUTSIDE=45~%uint8 LEFT_EYE_TOP_1=44~%uint8 LEFT_EYE_TOP_2=43~%uint8 LEFT_EYE_INSIDE=42~%uint8 LEFT_EYE_BOTTOM_1=46~%uint8 LEFT_EYE_BOTTOM_2=47~%~%uint8 LEFT_PUPIL=69~%~%uint8 SELLION=27~%uint8 NOSE_1=28~%uint8 NOSE_2=29~%uint8 NOSE=30~%~%uint8 NOSTRIL_1=31~%uint8 NOSTRIL_2=32~%uint8 NOSTRIL_3=33~%uint8 NOSTRIL_4=34~%uint8 NOSTRIL_5=35~%~%uint8 MOUTH_OUTER_RIGHT=48~%uint8 MOUTH_OUTER_TOP_1=49~%uint8 MOUTH_OUTER_TOP_2=50~%uint8 MOUTH_OUTER_TOP_3=51~%uint8 MOUTH_OUTER_TOP_4=52~%uint8 MOUTH_OUTER_TOP_5=53~%uint8 MOUTH_OUTER_LEFT=54~%uint8 MOUTH_OUTER_BOTTOM_1=59~%uint8 MOUTH_OUTER_BOTTOM_2=58~%uint8 MOUTH_OUTER_BOTTOM_3=57~%uint8 MOUTH_OUTER_BOTTOM_4=56~%uint8 MOUTH_OUTER_BOTTOM_5=55~%~%uint8 MOUTH_INNER_RIGHT=60~%uint8 MOUTH_INNER_TOP_1=61~%uint8 MOUTH_INNER_TOP_2=62~%uint8 MOUTH_INNER_TOP_3=63~%uint8 MOUTH_INNER_LEFT=64~%uint8 MOUTH_INNER_BOTTOM_1=67~%uint8 MOUTH_INNER_BOTTOM_2=66~%uint8 MOUTH_INNER_BOTTOM_3=65~%~%# array of 70 landmark normalized coordinates, one per landmark, ordered per landmarks codes~%NormalizedPointOfInterest2D[] landmarks~%~%uint32 height # image height in pixels, that is, number of rows~%uint32 width # image width in pixels, that is, number of columns~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: hri_msgs/NormalizedPointOfInterest2D~%# This contains the position of a point of interest (typically in an image)~%# the coordinates are always normalized and must belong to [0.,1.].~%# c is a confidence level (between 0. and 1.) associated to that POI~%float32 x~%float32 y~%float32 c~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FacialLandmarks)))
  "Returns full string definition for message of type 'FacialLandmarks"
  (cl:format cl:nil "# This message contains a list of facial features detected on a face~%# (0, 0) is at top-left corner of image~%# Features' coordinates are expressed in normalised pixel coordinates ~%# (in the range [0., 1.]), from the top-left corner.~%Header header~%~%# Facial landmarks codes~%# Follows dlib and OpenPose convention~%# https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/02_output.md#face-output-format~%uint8 RIGHT_EAR=0~%uint8 RIGHT_PROFILE_1=1~%uint8 RIGHT_PROFILE_2=2~%uint8 RIGHT_PROFILE_3=3~%uint8 RIGHT_PROFILE_4=4~%uint8 RIGHT_PROFILE_5=5~%uint8 RIGHT_PROFILE_6=6~%uint8 RIGHT_PROFILE_7=7~%~%uint8 MENTON=8~%~%uint8 LEFT_EAR=16~%uint8 LEFT_PROFILE_1=15~%uint8 LEFT_PROFILE_2=14~%uint8 LEFT_PROFILE_3=13~%uint8 LEFT_PROFILE_4=12~%uint8 LEFT_PROFILE_5=11~%uint8 LEFT_PROFILE_6=10~%uint8 LEFT_PROFILE_7=9~%~%uint8 RIGHT_EYEBROW_OUTSIDE=17~%uint8 RIGHT_EYEBROW_1=18~%uint8 RIGHT_EYEBROW_2=19~%uint8 RIGHT_EYEBROW_3=20~%uint8 RIGHT_EYEBROW_INSIDE=21~%~%uint8 RIGHT_EYE_OUTSIDE=36~%uint8 RIGHT_EYE_TOP_1=37~%uint8 RIGHT_EYE_TOP_2=38~%uint8 RIGHT_EYE_INSIDE=39~%uint8 RIGHT_EYE_BOTTOM_1=41~%uint8 RIGHT_EYE_BOTTOM_2=40~%~%uint8 RIGHT_PUPIL=68~%~%uint8 LEFT_EYEBROW_OUTSIDE=26~%uint8 LEFT_EYEBROW_1=25~%uint8 LEFT_EYEBROW_2=24~%uint8 LEFT_EYEBROW_3=23~%uint8 LEFT_EYEBROW_INSIDE=22~%~%uint8 LEFT_EYE_OUTSIDE=45~%uint8 LEFT_EYE_TOP_1=44~%uint8 LEFT_EYE_TOP_2=43~%uint8 LEFT_EYE_INSIDE=42~%uint8 LEFT_EYE_BOTTOM_1=46~%uint8 LEFT_EYE_BOTTOM_2=47~%~%uint8 LEFT_PUPIL=69~%~%uint8 SELLION=27~%uint8 NOSE_1=28~%uint8 NOSE_2=29~%uint8 NOSE=30~%~%uint8 NOSTRIL_1=31~%uint8 NOSTRIL_2=32~%uint8 NOSTRIL_3=33~%uint8 NOSTRIL_4=34~%uint8 NOSTRIL_5=35~%~%uint8 MOUTH_OUTER_RIGHT=48~%uint8 MOUTH_OUTER_TOP_1=49~%uint8 MOUTH_OUTER_TOP_2=50~%uint8 MOUTH_OUTER_TOP_3=51~%uint8 MOUTH_OUTER_TOP_4=52~%uint8 MOUTH_OUTER_TOP_5=53~%uint8 MOUTH_OUTER_LEFT=54~%uint8 MOUTH_OUTER_BOTTOM_1=59~%uint8 MOUTH_OUTER_BOTTOM_2=58~%uint8 MOUTH_OUTER_BOTTOM_3=57~%uint8 MOUTH_OUTER_BOTTOM_4=56~%uint8 MOUTH_OUTER_BOTTOM_5=55~%~%uint8 MOUTH_INNER_RIGHT=60~%uint8 MOUTH_INNER_TOP_1=61~%uint8 MOUTH_INNER_TOP_2=62~%uint8 MOUTH_INNER_TOP_3=63~%uint8 MOUTH_INNER_LEFT=64~%uint8 MOUTH_INNER_BOTTOM_1=67~%uint8 MOUTH_INNER_BOTTOM_2=66~%uint8 MOUTH_INNER_BOTTOM_3=65~%~%# array of 70 landmark normalized coordinates, one per landmark, ordered per landmarks codes~%NormalizedPointOfInterest2D[] landmarks~%~%uint32 height # image height in pixels, that is, number of rows~%uint32 width # image width in pixels, that is, number of columns~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: hri_msgs/NormalizedPointOfInterest2D~%# This contains the position of a point of interest (typically in an image)~%# the coordinates are always normalized and must belong to [0.,1.].~%# c is a confidence level (between 0. and 1.) associated to that POI~%float32 x~%float32 y~%float32 c~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FacialLandmarks>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'landmarks) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FacialLandmarks>))
  "Converts a ROS message object to a list"
  (cl:list 'FacialLandmarks
    (cl:cons ':header (header msg))
    (cl:cons ':landmarks (landmarks msg))
    (cl:cons ':height (height msg))
    (cl:cons ':width (width msg))
))
