// Generated by gencpp from file py_trees_msgs/CloseBlackboardWatcherResponse.msg
// DO NOT EDIT!


#ifndef PY_TREES_MSGS_MESSAGE_CLOSEBLACKBOARDWATCHERRESPONSE_H
#define PY_TREES_MSGS_MESSAGE_CLOSEBLACKBOARDWATCHERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace py_trees_msgs
{
template <class ContainerAllocator>
struct CloseBlackboardWatcherResponse_
{
  typedef CloseBlackboardWatcherResponse_<ContainerAllocator> Type;

  CloseBlackboardWatcherResponse_()
    : result(false)  {
    }
  CloseBlackboardWatcherResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CloseBlackboardWatcherResponse_

typedef ::py_trees_msgs::CloseBlackboardWatcherResponse_<std::allocator<void> > CloseBlackboardWatcherResponse;

typedef boost::shared_ptr< ::py_trees_msgs::CloseBlackboardWatcherResponse > CloseBlackboardWatcherResponsePtr;
typedef boost::shared_ptr< ::py_trees_msgs::CloseBlackboardWatcherResponse const> CloseBlackboardWatcherResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator1> & lhs, const ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator1> & lhs, const ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace py_trees_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "py_trees_msgs/CloseBlackboardWatcherResponse";
  }

  static const char* value(const ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# response stating successful shutdown of sub_blackboard\n"
"bool result\n"
"\n"
;
  }

  static const char* value(const ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CloseBlackboardWatcherResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::py_trees_msgs::CloseBlackboardWatcherResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PY_TREES_MSGS_MESSAGE_CLOSEBLACKBOARDWATCHERRESPONSE_H
