// Generated by gencpp from file py_trees_msgs/CloseBlackboardWatcher.msg
// DO NOT EDIT!


#ifndef PY_TREES_MSGS_MESSAGE_CLOSEBLACKBOARDWATCHER_H
#define PY_TREES_MSGS_MESSAGE_CLOSEBLACKBOARDWATCHER_H

#include <ros/service_traits.h>


#include <py_trees_msgs/CloseBlackboardWatcherRequest.h>
#include <py_trees_msgs/CloseBlackboardWatcherResponse.h>


namespace py_trees_msgs
{

struct CloseBlackboardWatcher
{

typedef CloseBlackboardWatcherRequest Request;
typedef CloseBlackboardWatcherResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CloseBlackboardWatcher
} // namespace py_trees_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::py_trees_msgs::CloseBlackboardWatcher > {
  static const char* value()
  {
    return "55b7efb7a62750406d3968e9c1907525";
  }

  static const char* value(const ::py_trees_msgs::CloseBlackboardWatcher&) { return value(); }
};

template<>
struct DataType< ::py_trees_msgs::CloseBlackboardWatcher > {
  static const char* value()
  {
    return "py_trees_msgs/CloseBlackboardWatcher";
  }

  static const char* value(const ::py_trees_msgs::CloseBlackboardWatcher&) { return value(); }
};


// service_traits::MD5Sum< ::py_trees_msgs::CloseBlackboardWatcherRequest> should match
// service_traits::MD5Sum< ::py_trees_msgs::CloseBlackboardWatcher >
template<>
struct MD5Sum< ::py_trees_msgs::CloseBlackboardWatcherRequest>
{
  static const char* value()
  {
    return MD5Sum< ::py_trees_msgs::CloseBlackboardWatcher >::value();
  }
  static const char* value(const ::py_trees_msgs::CloseBlackboardWatcherRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::py_trees_msgs::CloseBlackboardWatcherRequest> should match
// service_traits::DataType< ::py_trees_msgs::CloseBlackboardWatcher >
template<>
struct DataType< ::py_trees_msgs::CloseBlackboardWatcherRequest>
{
  static const char* value()
  {
    return DataType< ::py_trees_msgs::CloseBlackboardWatcher >::value();
  }
  static const char* value(const ::py_trees_msgs::CloseBlackboardWatcherRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::py_trees_msgs::CloseBlackboardWatcherResponse> should match
// service_traits::MD5Sum< ::py_trees_msgs::CloseBlackboardWatcher >
template<>
struct MD5Sum< ::py_trees_msgs::CloseBlackboardWatcherResponse>
{
  static const char* value()
  {
    return MD5Sum< ::py_trees_msgs::CloseBlackboardWatcher >::value();
  }
  static const char* value(const ::py_trees_msgs::CloseBlackboardWatcherResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::py_trees_msgs::CloseBlackboardWatcherResponse> should match
// service_traits::DataType< ::py_trees_msgs::CloseBlackboardWatcher >
template<>
struct DataType< ::py_trees_msgs::CloseBlackboardWatcherResponse>
{
  static const char* value()
  {
    return DataType< ::py_trees_msgs::CloseBlackboardWatcher >::value();
  }
  static const char* value(const ::py_trees_msgs::CloseBlackboardWatcherResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PY_TREES_MSGS_MESSAGE_CLOSEBLACKBOARDWATCHER_H
