// Generated by gencpp from file py_trees_msgs/DockFeedback.msg
// DO NOT EDIT!


#ifndef PY_TREES_MSGS_MESSAGE_DOCKFEEDBACK_H
#define PY_TREES_MSGS_MESSAGE_DOCKFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace py_trees_msgs
{
template <class ContainerAllocator>
struct DockFeedback_
{
  typedef DockFeedback_<ContainerAllocator> Type;

  DockFeedback_()
    : percentage_completed(0.0)  {
    }
  DockFeedback_(const ContainerAllocator& _alloc)
    : percentage_completed(0.0)  {
  (void)_alloc;
    }



   typedef float _percentage_completed_type;
  _percentage_completed_type percentage_completed;





  typedef boost::shared_ptr< ::py_trees_msgs::DockFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::py_trees_msgs::DockFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DockFeedback_

typedef ::py_trees_msgs::DockFeedback_<std::allocator<void> > DockFeedback;

typedef boost::shared_ptr< ::py_trees_msgs::DockFeedback > DockFeedbackPtr;
typedef boost::shared_ptr< ::py_trees_msgs::DockFeedback const> DockFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::py_trees_msgs::DockFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::py_trees_msgs::DockFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::py_trees_msgs::DockFeedback_<ContainerAllocator1> & lhs, const ::py_trees_msgs::DockFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percentage_completed == rhs.percentage_completed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::py_trees_msgs::DockFeedback_<ContainerAllocator1> & lhs, const ::py_trees_msgs::DockFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace py_trees_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::py_trees_msgs::DockFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::py_trees_msgs::DockFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::py_trees_msgs::DockFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::py_trees_msgs::DockFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::py_trees_msgs::DockFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::py_trees_msgs::DockFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::py_trees_msgs::DockFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26e2c7154b190781742892deccb6c8f0";
  }

  static const char* value(const ::py_trees_msgs::DockFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26e2c7154b190781ULL;
  static const uint64_t static_value2 = 0x742892deccb6c8f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::py_trees_msgs::DockFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "py_trees_msgs/DockFeedback";
  }

  static const char* value(const ::py_trees_msgs::DockFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::py_trees_msgs::DockFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"####################\n"
"# Feedback\n"
"####################\n"
"\n"
"float32 percentage_completed\n"
"\n"
;
  }

  static const char* value(const ::py_trees_msgs::DockFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::py_trees_msgs::DockFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage_completed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DockFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::py_trees_msgs::DockFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::py_trees_msgs::DockFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percentage_completed: ";
    Printer<float>::stream(s, indent + "  ", v.percentage_completed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PY_TREES_MSGS_MESSAGE_DOCKFEEDBACK_H
