// Auto-generated. Do not edit!

// (in-package py_trees_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class RotateFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.percentage_completed = null;
      this.angle_rotated = null;
    }
    else {
      if (initObj.hasOwnProperty('percentage_completed')) {
        this.percentage_completed = initObj.percentage_completed
      }
      else {
        this.percentage_completed = 0.0;
      }
      if (initObj.hasOwnProperty('angle_rotated')) {
        this.angle_rotated = initObj.angle_rotated
      }
      else {
        this.angle_rotated = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type RotateFeedback
    // Serialize message field [percentage_completed]
    bufferOffset = _serializer.float32(obj.percentage_completed, buffer, bufferOffset);
    // Serialize message field [angle_rotated]
    bufferOffset = _serializer.float32(obj.angle_rotated, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type RotateFeedback
    let len;
    let data = new RotateFeedback(null);
    // Deserialize message field [percentage_completed]
    data.percentage_completed = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [angle_rotated]
    data.angle_rotated = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'py_trees_msgs/RotateFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f1088922e17b4a9f4319356ac8d99645';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    ####################
    # Feedback
    ####################
    
    float32 percentage_completed
    float32 angle_rotated          # in radians
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new RotateFeedback(null);
    if (msg.percentage_completed !== undefined) {
      resolved.percentage_completed = msg.percentage_completed;
    }
    else {
      resolved.percentage_completed = 0.0
    }

    if (msg.angle_rotated !== undefined) {
      resolved.angle_rotated = msg.angle_rotated;
    }
    else {
      resolved.angle_rotated = 0.0
    }

    return resolved;
    }
};

module.exports = RotateFeedback;
