(cl:defpackage py_trees_msgs-srv
  (:use )
  (:export
   "CLOSEBLACKBOARDWATCHER"
   "<CLOSEBLACKBOARDWATCHER-REQUEST>"
   "CLOSEBLACKBOARDWATCHER-REQUEST"
   "<CLOSEBLACKBOARDWATCHER-RESPONSE>"
   "CLOSEBLACKBOARDWATCHER-RESPONSE"
   "GETBLACKBOARDVARIABLES"
   "<GETBLACKBOARDVARIABLES-REQUEST>"
   "GETBLACKBOARDVARIABLES-REQUEST"
   "<GETBLACKBOARDVARIABLES-RESPONSE>"
   "GETBLACKBOARDVARIABLES-RESPONSE"
   "OPENBLACKBOARDWATCHER"
   "<OPENBLACKBOARDWATCHER-REQUEST>"
   "OPENBLACKBOARDWATCHER-REQUEST"
   "<OPENBLACKBOARDWATCHER-RESPONSE>"
   "OPENBLACKBOARDWATCHER-RESPONSE"
  ))

