// Generated by gencpp from file hri_msgs/Group.msg
// DO NOT EDIT!


#ifndef HRI_MSGS_MESSAGE_GROUP_H
#define HRI_MSGS_MESSAGE_GROUP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace hri_msgs
{
template <class ContainerAllocator>
struct Group_
{
  typedef Group_<ContainerAllocator> Type;

  Group_()
    : header()
    , group_id()
    , members()  {
    }
  Group_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , group_id(_alloc)
    , members(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _group_id_type;
  _group_id_type group_id;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _members_type;
  _members_type members;





  typedef boost::shared_ptr< ::hri_msgs::Group_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hri_msgs::Group_<ContainerAllocator> const> ConstPtr;

}; // struct Group_

typedef ::hri_msgs::Group_<std::allocator<void> > Group;

typedef boost::shared_ptr< ::hri_msgs::Group > GroupPtr;
typedef boost::shared_ptr< ::hri_msgs::Group const> GroupConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hri_msgs::Group_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hri_msgs::Group_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hri_msgs::Group_<ContainerAllocator1> & lhs, const ::hri_msgs::Group_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.group_id == rhs.group_id &&
    lhs.members == rhs.members;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hri_msgs::Group_<ContainerAllocator1> & lhs, const ::hri_msgs::Group_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hri_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hri_msgs::Group_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hri_msgs::Group_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hri_msgs::Group_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hri_msgs::Group_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hri_msgs::Group_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hri_msgs::Group_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hri_msgs::Group_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76be953e6ddf78f60b879c220d0a3c32";
  }

  static const char* value(const ::hri_msgs::Group_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76be953e6ddf78f6ULL;
  static const uint64_t static_value2 = 0x0b879c220d0a3c32ULL;
};

template<class ContainerAllocator>
struct DataType< ::hri_msgs::Group_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hri_msgs/Group";
  }

  static const char* value(const ::hri_msgs::Group_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hri_msgs::Group_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"string group_id\n"
"\n"
"# List of person IDs of the people in this group\n"
"string[] members\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::hri_msgs::Group_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hri_msgs::Group_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.group_id);
      stream.next(m.members);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Group_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hri_msgs::Group_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hri_msgs::Group_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "group_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.group_id);
    s << indent << "members[]" << std::endl;
    for (size_t i = 0; i < v.members.size(); ++i)
    {
      s << indent << "  members[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.members[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRI_MSGS_MESSAGE_GROUP_H
