// Generated by gencpp from file hri_msgs/IdsList.msg
// DO NOT EDIT!


#ifndef HRI_MSGS_MESSAGE_IDSLIST_H
#define HRI_MSGS_MESSAGE_IDSLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace hri_msgs
{
template <class ContainerAllocator>
struct IdsList_
{
  typedef IdsList_<ContainerAllocator> Type;

  IdsList_()
    : header()
    , ids()  {
    }
  IdsList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ids(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _ids_type;
  _ids_type ids;





  typedef boost::shared_ptr< ::hri_msgs::IdsList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hri_msgs::IdsList_<ContainerAllocator> const> ConstPtr;

}; // struct IdsList_

typedef ::hri_msgs::IdsList_<std::allocator<void> > IdsList;

typedef boost::shared_ptr< ::hri_msgs::IdsList > IdsListPtr;
typedef boost::shared_ptr< ::hri_msgs::IdsList const> IdsListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hri_msgs::IdsList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hri_msgs::IdsList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hri_msgs::IdsList_<ContainerAllocator1> & lhs, const ::hri_msgs::IdsList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ids == rhs.ids;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hri_msgs::IdsList_<ContainerAllocator1> & lhs, const ::hri_msgs::IdsList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hri_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hri_msgs::IdsList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hri_msgs::IdsList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hri_msgs::IdsList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hri_msgs::IdsList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hri_msgs::IdsList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hri_msgs::IdsList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hri_msgs::IdsList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84a63f55b5676f78b625e8a8bb809fe5";
  }

  static const char* value(const ::hri_msgs::IdsList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84a63f55b5676f78ULL;
  static const uint64_t static_value2 = 0xb625e8a8bb809fe5ULL;
};

template<class ContainerAllocator>
struct DataType< ::hri_msgs::IdsList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hri_msgs/IdsList";
  }

  static const char* value(const ::hri_msgs::IdsList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hri_msgs::IdsList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message encodes a list of ROS4HRI IDs (eg face ids, body ids, person\n"
"# ids...).\n"
"# It is for instance published on /humans/faces/tracked to access the list of\n"
"# currently detected faces.\n"
"Header header\n"
"string[] ids\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::hri_msgs::IdsList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hri_msgs::IdsList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IdsList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hri_msgs::IdsList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hri_msgs::IdsList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRI_MSGS_MESSAGE_IDSLIST_H
